# Generated by Django 4.0.1 on 2024-02-25 17:44

import default_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('access_key', models.CharField(max_length=100)),
                ('timeseries_endpoint', models.CharField(blank=True, default='', help_text='Use {0} for access_key, {1} for base_currency, {2} for date_from, {3} for date_to. For example, url could be http://data.fixer.io/api/timeseries?access_key={0}&base={1}&start_date={2}&end_date={3}', max_length=200)),
                ('latest_endpoint', models.CharField(blank=True, default='', help_text='Use {0} for access_key and {1} for base_curreny. For example, http://data.fixer.io/api/latest?access_key={0}&base={1}', max_length=200)),
                ('historical_hardcoded_json', models.JSONField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-is_default', '-priority'),
            },
            bases=(models.Model, default_app.models.ProviderInterface),
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(db_index=True)),
                ('rate_value', models.DecimalField(db_index=True, decimal_places=6, max_digits=18)),
                ('exchanged_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default_app.currency')),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='default_app.currency')),
            ],
            options={
                'ordering': ('valuation_date', 'source_currency', 'exchanged_currency'),
                'unique_together': {('source_currency', 'exchanged_currency', 'valuation_date')},
            },
        ),
    ]
